services:
  tests:
    build: .
    image: unraid/bsdk-tests:latest
    env_file:
      - .env
    environment:
      BROWSERSTACK_USERNAME: ${BROWSERSTACK_USERNAME}
      BROWSERSTACK_ACCESS_KEY: ${BROWSERSTACK_ACCESS_KEY}
      BROWSERSTACK_LOCAL: "false"
      BROWSERSTACK_BUILD_SUFFIX: "${HOSTNAME:-unraid}"
    # Optional: limit resources
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8g
