services:
  app:
    image: node:18.20.4
    container_name: BrowserTests
    working_dir: /app
    volumes:
      - .:/app
    command: bash -lc "npm ci --no-audit --no-fund && npm test"
    ports:
      - "3000:3000"
